### ISSUE TITLE
[WOC] Setup linting and other necessary repo bioler-plates

### ISSUE THREAD

**Issue by abhibhaw** [GEPTON-INFOTECH/galena#2]
You may not require to add everything but this pr can be used as [reference](https://github.com/dscnitrourkela/project-oregano/pull/1/files)

**Comment by randiepathirage** [comment]
@abhibhaw I would like to work on this.

**Comment by randiepathirage** [comment]
@abhibhaw Is this project is gonna use .editorconfig or Js standard style is enough?

**Comment by abhibhaw** [comment]
Editor config isn't required

**Comment by abhibhaw** [comment]
fixed
