### ISSUE TITLE
[WOC] Redesign Website

### ISSUE THREAD

**Issue by Keshraf** [GEPTON-INFOTECH/galena#6]
**Is your feature request related to a problem? Please describe.**
Great Design is an important aspect of a service-providing website. It attracts new customers and retains the old customers.

**Describe the solution you'd like**
A clear, well-formatted website that reflects the company's level and work ethic.

**Additional context**

![Landing Page (3)](https://user-images.githubusercontent.com/82109991/147753486-fd05e8bc-78b3-44e2-99f5-f3d71c566fc4.png)

### IMPORTANT

Hello folks 👋,
I have redesigned the website and wanted your take on it as well.

If you have any suggestions or comments regarding the design, please don't hesitate to comment below.

**Comment by Keshraf** [comment]
### Here is the Template for the Products Sections 

![image](https://user-images.githubusercontent.com/82109991/149630400-cb1f8f7b-cf96-4b02-905c-a91e5897bec2.png)

**Comment by abhibhaw** [comment]
Stale
