### ISSUE TITLE
Create Landing Component

### ISSUE THREAD

**Issue by abhibhaw** [GEPTON-INFOTECH/galena#7]
![landing](https://user-images.githubusercontent.com/39991296/148687979-37a3ba2c-eff2-4b96-bee1-b3f4e0d9aafd.png)

**Comment by randiepathirage** [comment]
@abhibhaw I would like to work on this.

**Comment by abhibhaw** [comment]
Sure @randiepathirage go ahead

**Comment by abhibhaw** [comment]
fixed
